### ISSUE TITLE
Error message.

### ISSUE THREAD

**Issue by DenisXuGithub** [zmcx16/MahoMangaDownloader_release#1]
日安。

我剛剛使用 V21.1 的版本，在漫畫櫃。
我直接在目錄頁，對某集單行本，按右鍵，複製連結網址。

結果會出現這兩種訊息。
![螢幕擷取畫面 2024-12-25 191148](https://github.com/user-attachments/assets/e0825764-0c31-4415-8882-c979d653e9b5)
![螢幕擷取畫面 2024-12-25 191246](https://github.com/user-attachments/assets/bbc6df99-f1a8-436e-a0aa-400ca38d377f)
然後就沒有動靜了...

我不知道問題出在哪？
感謝。

**Comment by zmcx16** [comment]
您好, 我剛剛測試漫畫櫃可以正常下載, 麻煩提供有問題的網址, 或是提供log資料夾的log內容, 我在查看看原因。

**Comment by DenisXuGithub** [comment]
日安。

我是在這一頁 → https://tw.manhuagui.com/comic/1128/
直接對 100 卷按右鍵，複製連結網址。
然後就跳首樓的錯誤訊息。

選項裡面的所有設定都是預設值，沒有更動。
這是要下載時的畫面 ↓
![螢幕擷取畫面 2024-12-26 113830](https://github.com/user-attachments/assets/961324a7-8bd5-4a42-ad7a-75c9100745f5)

這是 log ↓
[20241225.log](https://github.com/user-attachments/files/18249303/20241225.log)

謝謝您。

**Comment by zmcx16** [comment]
您好, 像漫畫櫃那類有話集數的網頁只支援複製該漫畫頁的首頁網址, 之後會跳出視窗讓使用者決定要下載哪幾話, 沒有支援複製單一話集數網址。

**Comment by DenisXuGithub** [comment]
日安。

原來如此！
目前正常執行中。

感謝您！ :D

**Comment by zmcx16** [comment]
不客氣, 問題有解決就好~。
